apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: NodePort
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081