apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: service-b:latest
        imagePullPolicy: IfNotPresent  # Add this line
        ports:
        - containerPort: 8081
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: SECRET_KEY
        - name: CONFIG_MAP_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: CONFIG_MAP_KEY